"""add_weight_versions

# ruff: noqa: E501

Revision ID: 25b1dfc0e341
Revises: 0002
Create Date: 2026-08-05 02:42:29.357143
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "25b1dfc0e341"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weight_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("technical", sa.Float(), nullable=False),
        sa.Column("sentiment", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weight_versions")),
        sa.UniqueConstraint("version", name=op.f("uq_weight_versions_version")),
    )
    op.alter_column(
        "instruments",
        "point",
        existing_type=sa.NUMERIC(precision=18, scale=10),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "instruments",
        "contract_size",
        existing_type=sa.NUMERIC(precision=18, scale=4),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("ck_instruments_ck_instruments_contract_size_positivo"), "instruments", type_="check"
    )
    op.drop_constraint(
        op.f("ck_instruments_ck_instruments_digits_nao_negativo"), "instruments", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_instruments_contract_size_positivo"), "instruments", "contract_size > 0"
    )
    op.create_check_constraint(
        op.f("ck_instruments_digits_nao_negativo"), "instruments", "digits >= 0"
    )
    op.drop_constraint(
        op.f("ck_outcomes_ck_outcomes_duration_nao_negativa"), "outcomes", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_outcomes_duration_nao_negativa"), "outcomes", "duration_seconds >= 0"
    )
    op.drop_constraint(op.f("ck_signals_ck_signals_confidence_0_1"), "signals", type_="check")
    op.drop_constraint(op.f("ck_signals_ck_signals_fused_score_menos1_1"), "signals", type_="check")
    op.drop_constraint(
        op.f("ck_signals_ck_signals_sentiment_score_menos1_1"), "signals", type_="check"
    )
    op.drop_constraint(
        op.f("ck_signals_ck_signals_technical_score_menos1_1"), "signals", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_signals_confidence_0_1"), "signals", "confidence >= 0 AND confidence <= 1"
    )
    op.create_check_constraint(
        op.f("ck_signals_fused_score_menos1_1"), "signals", "fused_score >= -1 AND fused_score <= 1"
    )
    op.create_check_constraint(
        op.f("ck_signals_sentiment_score_menos1_1"),
        "signals",
        "sentiment_score IS NULL OR (sentiment_score >= -1 AND sentiment_score <= 1)",
    )
    op.create_check_constraint(
        op.f("ck_signals_technical_score_menos1_1"),
        "signals",
        "technical_score IS NULL OR (technical_score >= -1 AND technical_score <= 1)",
    )
    op.drop_constraint(op.f("uq_trades_client_request_id"), "trades", type_="unique")
    op.drop_index(op.f("ix_trades_client_request_id"), table_name="trades")
    op.create_index(
        op.f("ix_trades_client_request_id"), "trades", ["client_request_id"], unique=True
    )
    op.drop_constraint(op.f("ck_trades_ck_trades_stop_loss_positivo"), "trades", type_="check")
    op.drop_constraint(op.f("ck_trades_ck_trades_take_profit_positivo"), "trades", type_="check")
    op.drop_constraint(op.f("ck_trades_ck_trades_volume_positivo"), "trades", type_="check")
    op.create_check_constraint(op.f("ck_trades_stop_loss_positivo"), "trades", "stop_loss > 0")
    op.create_check_constraint(
        op.f("ck_trades_take_profit_positivo"), "trades", "take_profit IS NULL OR take_profit > 0"
    )
    op.create_check_constraint(op.f("ck_trades_volume_positivo"), "trades", "volume > 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_trades_volume_positivo"), "trades", type_="check")
    op.drop_constraint(op.f("ck_trades_take_profit_positivo"), "trades", type_="check")
    op.drop_constraint(op.f("ck_trades_stop_loss_positivo"), "trades", type_="check")
    op.create_check_constraint(
        op.f("ck_trades_ck_trades_volume_positivo"), "trades", "volume > 0::double precision"
    )
    op.create_check_constraint(
        op.f("ck_trades_ck_trades_take_profit_positivo"),
        "trades",
        "take_profit IS NULL OR take_profit > 0::double precision",
    )
    op.create_check_constraint(
        op.f("ck_trades_ck_trades_stop_loss_positivo"), "trades", "stop_loss > 0::double precision"
    )
    op.drop_index(op.f("ix_trades_client_request_id"), table_name="trades")
    op.create_index(
        op.f("ix_trades_client_request_id"), "trades", ["client_request_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_trades_client_request_id"),
        "trades",
        ["client_request_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(op.f("ck_signals_technical_score_menos1_1"), "signals", type_="check")
    op.drop_constraint(op.f("ck_signals_sentiment_score_menos1_1"), "signals", type_="check")
    op.drop_constraint(op.f("ck_signals_fused_score_menos1_1"), "signals", type_="check")
    op.drop_constraint(op.f("ck_signals_confidence_0_1"), "signals", type_="check")
    op.create_check_constraint(
        op.f("ck_signals_ck_signals_technical_score_menos1_1"),
        "signals",
        "technical_score IS NULL OR technical_score >= '-1'::integer::double precision AND technical_score <= 1::double precision",  # noqa: E501
    )
    op.create_check_constraint(
        op.f("ck_signals_ck_signals_sentiment_score_menos1_1"),
        "signals",
        "sentiment_score IS NULL OR sentiment_score >= '-1'::integer::double precision AND sentiment_score <= 1::double precision",  # noqa: E501
    )
    op.create_check_constraint(
        op.f("ck_signals_ck_signals_fused_score_menos1_1"),
        "signals",
        "fused_score >= '-1'::integer::double precision AND fused_score <= 1::double precision",
    )
    op.create_check_constraint(
        op.f("ck_signals_ck_signals_confidence_0_1"),
        "signals",
        "confidence >= 0::double precision AND confidence <= 1::double precision",
    )
    op.drop_constraint(op.f("ck_outcomes_duration_nao_negativa"), "outcomes", type_="check")
    op.create_check_constraint(
        op.f("ck_outcomes_ck_outcomes_duration_nao_negativa"), "outcomes", "duration_seconds >= 0"
    )
    op.drop_constraint(op.f("ck_instruments_digits_nao_negativo"), "instruments", type_="check")
    op.drop_constraint(op.f("ck_instruments_contract_size_positivo"), "instruments", type_="check")
    op.create_check_constraint(
        op.f("ck_instruments_ck_instruments_digits_nao_negativo"), "instruments", "digits >= 0"
    )
    op.create_check_constraint(
        op.f("ck_instruments_ck_instruments_contract_size_positivo"),
        "instruments",
        "contract_size > 0::numeric",
    )
    op.alter_column(
        "instruments",
        "contract_size",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=18, scale=4),
        existing_nullable=False,
    )
    op.alter_column(
        "instruments",
        "point",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=18, scale=10),
        existing_nullable=False,
    )
    op.drop_table("weight_versions")
    # ### end Alembic commands ###
